#!/bin/sh
### BEGIN INIT INFO
# Provides:          My Package Name
# Email:             miradnanali@gmail.com
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
set -e

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Awesome stuff my app can do"
NAME=program_name
USER=root

DAEMON=/usr/sbin/$NAME
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
CHUID=$USER

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
start()
{
  if is_running;
  then
    echo "$NAME is already running"
  else
    echo "Starting $NAME"
    if start-stop-daemon -b --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS;
    then
      cat /dev/null >> $PIDFILE
      pidof $NAME >> $PIDFILE
    fi
  fi
  echo "."
}

#
# Function that stops the daemon/service
#
stop()
{
  if is_running;
  then
    echo "Stopping $NAME";
    start-stop-daemon --stop --quiet --oknodo --retry=30 --pidfile $PIDFILE
  else
    echo "$NAME already stopped";
  fi

  if [ -f "$PIDFILE" ];
  then
    rm -f $PIDFILE
  fi

  echo "."
}

#
# Restart
#
restart() {
  stop && start
  return 0
}

#
# Checks if program is running
#
is_running() {
    [ -f "$PIDFILE" ]
}


case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
status)
    if is_running;
    then
      echo "Running"
    else
      echo "Stopped"
    fi
    ;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit
